# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'BookingOnlineApp' to match the target in your Xcode project.
target 'BookingOnlineApp' do

  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native'
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  # pod 'react-native-maps', path: '../'
  # pod 'react-native-google-maps', path: '../'  # <~~ if you need GoogleMaps support on iOS
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end